[package]
name = "text_emotions_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.0"
dict = "0.1.5"
encoding = "0.2.33"
linfa = "0.6.1"
linfa-bayes = "0.6.1" 
linfa-logistic = "0.6.1"
linfa-preprocessing = "0.6.1"
ndarray = "0.15.6"
ndarray-csv = "0.5.1"
ndarray-npy = "0.8.1"
serde = "1.0.152"
serde_json = "1.0.93"
linfa-svm = { git = "https://github.com/rust-ml/linfa.git", features = ["serde"], default-features = false }
#getrandom = { version = "0.2", features = ["js"] } used for compiling to WASM